apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate
              env:
                - name: RENOVATE_PLATFORM
                  value: 'github'
                - name: RENOVATE_REPOSITORIES
                  value: 'adamrlynch/k8s-stack'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: token
          restartPolicy: Never
