apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: wrsys
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: wrsys-github-token
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-sp
  namespace: renovate
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: 'external-secrets/azure-secret-sp'