apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: wrsys
spec:
  provider:
    azurekv:
      tenantId: 42579e0e-52ab-403f-a789-545d822085fb
      vaultUrl: "https://wrsys.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret