apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-upgrade
spec:
  interval: 10m
  chart:
    spec:
      chart: system-upgrade-controller
      version: "105.x"
      sourceRef:
        kind: HelmRepository
        name: rancher
  upgrade:
    crds: CreateReplace
