apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      version: '0.10.x'
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 60m
  upgrade:
    crds: CreateReplace