apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-catalog
  namespace: cnpg
spec:
  interval: 10m
  path: "./Debian/ClusterImageCatalog.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cnpg