apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 5m
  chart:
    spec:
      version: '24.x'
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 60m
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: wp.lynch.us.to
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      tls: true
    persistence:
      storageClass: csi-synology-synology-csi-nfs-retain
    volumePermissions:
      enabled: true
    metrics:
      enabled: true
    mariadb:
      enabled: false
    externalDatabase:
      host: mariadb-galera-primary.wrsys.svc.cluster.local
      user: wrsys
      database: wrsys
      existingSecret: mariadb-password