apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: true

  podSecurityContext:
    runAsUser: 0

  storage:
    size: 10Gi
    storageClassName: csi-synology-synology-csi-iscsi-retain

  username: wrsys
  passwordSecretKeyRef:
    name: mariadb-password
    key: mariadb-password
    generate: false
  database: wrsys

  replicas: 3

  galera:
    enabled: true

  metrics:
    enabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      memory: 4Gi

  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5

  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 5

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=3200MB
    max_allowed_packet=1GB

  nodeSelector:
    kubernetes.io/arch: amd64  

  affinity:
    antiAffinityEnabled: true

  podDisruptionBudget:
    maxUnavailable: 66%

  priorityClassName: system-node-critical