apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-password
  labels:
    "k8s.mariadb.com/watch": "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: wrsys
    kind: ClusterSecretStore
  data:
    - secretKey: mariadb-password
      remoteRef:
        key: wrsys-synology
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-sp
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: 'external-secrets/azure-secret-sp'