apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.x"
      sourceRef:
        name: cnpg
        kind: HelmRepository
