apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-synology
spec:
  interval: 5m
  chart:
    spec:
      version: '0.10.x'
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: csi-synology
      interval: 60m
  upgrade:
    crds: CreateReplace
  values:
    clientInfoSecret:
      name: synology-csi-client-info