apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-client-info
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: wrsys
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        client-info.yaml: |
          clients:
          - host: 10.0.0.10
            https: false        
            password: "{{ .password}}"
            port: 5000
            username: kubernetes
  data:
    - secretKey: password
      remoteRef:
        key: wrsys-synology
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-sp
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: 'external-secrets/azure-secret-sp'