apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wrsys
resources:
  - repository.yml
  - release.yml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: '1'
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-kube-state-metrics-config
    namespace: monitoring
    files:
      - flux-kube-state-metrics-config.yml
    options:
      labels:
        grafana_dashboard: '1'
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/flux
configurations:
  - kustomizeconfig.yml
