apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      version: '67.x'
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: flux-kube-state-metrics-config.yml
  values:
    additionalPrometheusRulesMap:
      rule-name:
        groups:
          - name: Flux
            rules:
              - alert: ReconciliationFailure
                expr: max(gotk_resource_info{ready="False"}) by (exported_namespace, name, customresource_kind)
                for: 10m
                labels:
                  severity: critical
                annotations:
                  summary: '{{ $labels.customresource_kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation has been failing for more than ten minutes.'
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - lynch.us.to
        paths:
          - /
          - /grafana/
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: flux
              orgId: 1
              type: file
              folder: Flux
              allowUiUpdates: false
              disableDeletion: true
              updateIntervalSeconds: 10
              editable: false
              options:
                path: /tmp/dashboards/flux
    prometheus:
      prometheusSpec:
        routePrefix: /prometheus/
        externalUrl: http://lynch.us.to/prometheus
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - lynch.us.to
        paths:
          - /prometheus/
      additionalPodMonitors:
        - name: 'flux-system'
          namespaceSelector:
            matchNames:
              - flux-system
          selector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - helm-controller
                  - source-controller
                  - kustomize-controller
                  - notification-controller
                  - image-automation-controller
                  - image-reflector-controller
          podMetricsEndpoints:
            - port: http-prom
              relabelings:
                - sourceLabels: [__meta_kubernetes_pod_phase]
                  action: keep
                  regex: Running
